#!/bin/bash
# Setup script for the SedCam Beaglebone. Run this script with sudo immediately
# upon booting into newly flashed SD card.

# definitions
HOME="/home/debian"
SEDCAM="$HOME/sedcam"

# check for root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root."
   exit 1
fi

# move to user home
cd $HOME

# updates
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y autoremove

# prepare home directory
rm -f $HOME/.gitconfig
rm -rf $HOME/bin

# clone sedcam repository
sudo -u debian git clone https://github.com/tjcrone/sedcam.git $SEDCAM

# ethernet setup
cp $SEDCAM/beaglebone/interfaces /etc/network/
chown root:root /etc/network/interfaces
service networking restart

# user configuration files
sudo -u debian cp sedcam/beaglebone/.bashrc ~
sudo -u debian cp sedcam/beaglebone/.gitconfig ~
sudo -u debian cp sedcam/beaglebone/.vimrc ~

# make prosilica programs
cd $SEDCAM/prosilica/list_cameras
sudo -u debian make

cd $SEDCAM/prosilica/change_ip
sudo -u debian make

cd $SEDCAM/prosilica/snap_image
sudo -u debian make
